---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    author: Harita
spec:
  type: Clusterip
  ports:
    - targetPort: 5432
      protocol: 5432
  selector:
      name: postgres
...