---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    author: Harita
spec:
  type: Clusterip
  ports:
    - targetPort: 6379
      protocol: 6060
  selector:
      name: redis-pod
...