---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    author: Harita
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      protocol: 80
  selector:
      name: result-app
...
