---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  labels:
    name: voting-app
    author: Harita
spec:
  replicas: 3
  selector:
    matchLabels:
     name: voting-app
  template:
    metadata:
     name: voting-app-pod
     labels:
       name: voting-application
    spec:
     containers:
      - name: myvoting-app
        image: dockersamples/examplevotingapp_vote
...