---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  labels:
    name: worker-app
    author: Harita
spec:
  replicas: 1
  selector:
    matchLabels:
     name: worker-app
  template:
    metadata:
     name: worker-app-pod
     labels:
       name: worker-app
    spec:
     containers:
      - name: myworkerapp
        image: dockersamples/examplevotingapp_worker
...